index:
    path: /
    controller: App\Controller\ProductController::index

new_product:
    path: /product/new
    controller: App\Controller\ProductController::new

edit_product:
    path: /product/edit/{id}
    controller: App\Controller\ProductController::edit
    requirements:
        id: '\d+'

delete_product:
    path: /product/delete/{id}
    controller: App\Controller\ProductController::delete
    requirements:
        id: '\d+'

export_spreadsheet:
    path: /export_spreadsheet
    controller: App\Controller\DemoPhpSpreadsheetController::index
    requirements:
        id: '\d+'